# Generated by Django 4.0.5 on 2022-08-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filme', models.CharField(max_length=50)),
                ('Descricao', models.TextField()),
                ('Gênero', models.CharField(max_length=50)),
                ('Idade', models.CharField(max_length=2)),
            ],
        ),
    ]
